### ISSUE TITLE
Raspberry Pi pinouts are wrong

### ISSUE THREAD

**Issue by ghost** [bibanon/Coreboot-ThinkPads#1]
I just successfully flashed a T60 with a Raspberry Pi, but the GPIO pinouts mentioned do not work at all.

The correct pinout is:

|  |  |  |
| --- | --- | --- |
| 1 | CS | Pi Pin #24 |
| 2 | MISO | Pi Pin #21 |
| 3 | Don't connect |  |
| 4 | GND | Pi Pin #25 |
| 5 | MOSI | Pi Pin #19 |
| 6 | CLK | Pi Pin #23 |
| 7 | Don't connect |  |
| 8 | 3.3V | Pi Pin #17 with an SST chip or Don't connect with a Macronix chip |

You will also need an older Raspbian image in order to get SPI to work. It failed for me on kernels 3.16 and above, but worked fine on 3.12.

**Comment by antonizoon** [comment]
Hey, thanks. I never managed to figure this one out, probably because the pinouts were insanely unclear. 

Could you explain to me how you did this? I'll be able to fix the guide to help others (or in fact, you can edit the wiki freely as well) It would definitely reduce the need for an expensive Bus Pirate (and I actually think I fried mine).

**Comment by antonizoon** [comment]
Ok, so actually there was nothing wrong with the table. The Raspberry Pi uses two different pin numbering systems, so I had to include both of them (the GPIO pins were on the rightmost column).

I guess that can be confusing, so I left only the GPIO one.

| Clip Pin # | SPI Pin Name | Pi GPIO Pin # |
| :-: | :-: | --: |
| 1 | `CS` | GPIO 24 |
| 2 | `MISO` | GPIO 21 |
| 3 | _not used_ | _not used_ |
| 4 | `GND` | GND 25 |
| 5 | `MOSI` | GPIO 19 |
| 6 | `CLK` | GPIO 23 |
| 7 | _not used_ | _not used_ |
| 8 | `3.3V` | SST: GPIO 17, Macronix: Don't Connect |

So, I assume you wired it up and used this command?

```
sudo ./flashrom_lenovobios_sst -p linux_spi:dev=/dev/spidev0.0 -r test.rom
```

Also, can you send me a photo of how it should be wired? That way, I won't get confused by the conflicting numbering systems myself.

**Comment by ghost** [comment]
The unclear part was mostly the image above:

![gpio](https://cloud.githubusercontent.com/assets/9902302/7549702/5d1219b8-f641-11e4-8199-1c6f62b8eba0.png)

It says, for instance, that GPIO 24 is pin 18 on the Raspberry Pi. But it's actually _pin_ 24 you have to connect to the chip's first pin. So the table is still incorrect. (At least, if the image is what you refer to.)

If I'd "transcribe" the GPIO pins, it would be like this:

| Clip Pin # | SPI Pin Name | Pi Pin # | GPIO Pin # |
| --- | --- | --- | --- |
| 1 | `CS` | 24 | `GPIO 8` |
| 2 | `MISO` | 21 | `GPIO 9` |
| 3 | - | - | - |
| 4 | `GND` | 25 | `Ground` |
| 5 | `MOSI` | 19 | `GPIO 10` |
| 6 | `CLK` | 23 | `GPIO 11` |
| 7 | - | - | - |
| 8 | `3.3V` | 17 `(SST only)` | `3V3` |
- Don't connect Pin 8 if you have a Macronix chip, but use the ThinkPad power supply instead.

I bought one of those "rainbow" cables with numbered wires to make it easier to connect. You'd just put a 26-pin cap on the Raspberry Pi's headers and only have to connect the wires on the other side.
After tracing back all the colours, I can really confirm that the numbers refer to the Raspberry Pi pins and _not_ the GPIO numbers. (1,3,5, etc. on the bottom row and 2,4,6, etc. on the top row.)

![pinout](https://cloud.githubusercontent.com/assets/9902302/7549735/94ac35ec-f642-11e4-8ee7-b0d3ba94a88c.jpg)

I wrote a blog post about my experience here: https://blogs.fsfe.org/the_unconventional/2015/05/08/flashing-coreboot-on-a-t60-with-a-raspberry-pi/

It also explains how I flashed the ROM, because as far as I'm aware, there is no `flashrom_lenovobios_*` for armhf. So I just cloned upstream flashrom 0.9.8 from svn and compiled it with GCC.

Because I have a Macronix chip, I ran `sudo ./flashrom -c "MX25L1605" -p linux_spi:dev=/dev/spidev0.0 -w /path/to/coreboot.rom` to write the ROM.

**Comment by antonizoon** [comment]
Ah, thanks for updating the wikipage. I was going to wait until I had actually independently tested it, but feel free to help where necessary.

**Comment by ghost** [comment]
I'd still be interested in your test results though. If there's anything I can help you with, don't hesitate to send me an e-mail.

I've re-read the wiki page as it is now, and this is how I can confirm it worked at least for me.
I'd be happy to hear if others are able to pull it off successfully as well.

**Comment by antonizoon** [comment]
Alright, I'll post it here on this github issue when I find out. Though I'll be flashing an X200 using a Raspberry Pi, since I'm elsewhere during summer and my Libreboot ThinkPads are in storage...
