### ISSUE TITLE
Add a free license

### ISSUE THREAD

**Issue by pizzamaker** [bibanon/Coreboot-ThinkPads#2]
I couldn't find a license for this project among the files. Could you please add a libre license? Thanks.

**Comment by GuyNoIRQ** [comment]
Oooh. I only figured out the way to and wrote up how to flash with the RPi to the X200. I can't really license the whole shebang. I'm happy to add a CC0 license to the stuff I wrote, but I don't hold the copyright for the majority of the work. Also I'm not certain how to go about segmenting it.

**Comment by pizzamaker** [comment]
Aw, that's a shame. Thanks anyway.

**Comment by antonizoon** [comment]
Hey there, I'm the original writer and manager of this wiki. I hereby release this entire guide under [Creative Commons Attribution 4.0](https://creativecommons.org/licenses/by/4.0/)

Also, thanks a bunch to Snuffeluffegus for creating the RPi flash method! I'll test it out right now.

**Comment by pizzamaker** [comment]
Fantastic! Thanks @antonizoon

**Comment by pizzamaker** [comment]
Come to think of it, it would be ideal if you had a LICENSE.md file with CC-BY-4.0's full text, for reference :)

**Comment by antonizoon** [comment]
Done, thanks: https://github.com/bibanon/Coreboot-ThinkPads/blob/master/LICENSE.md
