### ISSUE TITLE
Generilize GPIO so more programming boards can be added

### ISSUE THREAD

**Issue by tlaurion** [bibanon/Coreboot-ThinkPads#3]
Fell upon https://pinout.xyz website.

Will do for ch341a since the x200 soic16 SPI flash doesn't have proper documentation anywhere.

**Comment by antonizoon** [comment]
Thank you, please keep us updated.

**Comment by AkechiShiro** [comment]
Hi @tlaurion has this been abandoned ?

**Comment by tlaurion** [comment]
Was already done in so many orhtr projects, pinout explained under https://libreboot.org/docs/install/spi.html for example.
